"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { buildQualifiedSalesWhatsAppUrl, getSalesWhatsAppUrl } from "../lib/sales-contact";

const processSteps = [["01", "Crie", "Estruture o processo que importa."], ["02", "Atribua", "Defina quem precisa executar."], ["03", "Execute", "Registre a rotina pelo celular."], ["04", "Comprove", "Conecte respostas e evidências."], ["05", "Corrija", "Transforme desvios em ação."], ["06", "Acompanhe", "Consulte o histórico da operação."]];
const questions = [["O CheckFlow funciona no celular?", "Sim. A interface web é preparada para a execução pelo celular."], ["Preciso instalar alguma coisa?", "Não. O CheckFlow é acessado no navegador."], ["Posso registrar fotos?", "Sim, nos fluxos em que a evidência fotográfica é suportada."], ["Consigo saber quem executou?", "Sim. As execuções registram o responsável conforme o fluxo."], ["O histórico fica registrado?", "Sim. As execuções concluídas permanecem disponíveis no histórico."], ["O que acontece depois dos 14 dias?", "Após o piloto, avaliamos juntos o resultado e a continuidade da operação no CheckFlow."]];
const salesWhatsAppUrl = getSalesWhatsAppUrl(process.env.NEXT_PUBLIC_CHECKFLOW_SALES_WHATSAPP);
const demoVideoSrc: string | null = null;
const demoVideoPoster = "/marketing/checkflow-demo-poster.jpg";

function Arrow() { return <span aria-hidden="true" className="marketing-arrow">→</span>; }
function Check() { return <span aria-hidden="true" className="marketing-check">✓</span>; }
type Qualification = { name: string; company: string; operation: string; process: string };
const emptyQualification: Qualification = { name: "", company: "", operation: "", process: "" };

function PilotCta({ onOpen }: { onOpen: () => void }) {
  return salesWhatsAppUrl ? <button className="marketing-button primary" type="button" onClick={onOpen}>Começar meu piloto <Arrow /></button> : <span className="marketing-button primary marketing-button-unavailable" aria-disabled="true" aria-describedby="sales-contact-pending">Começar meu piloto <Arrow /></span>;
}

export default function MarketingPage() {
  const [qualificationOpen, setQualificationOpen] = useState(false);
  const [qualification, setQualification] = useState(emptyQualification);
  const [formError, setFormError] = useState("");
  const openerRef = useRef<HTMLElement | null>(null);
  const dialogRef = useRef<HTMLDivElement | null>(null);
  const openQualification = (event?: React.MouseEvent<HTMLElement>) => { openerRef.current = event?.currentTarget ?? document.activeElement as HTMLElement; setQualificationOpen(true); };
  const closeQualification = () => { setQualificationOpen(false); setFormError(""); };
  useEffect(() => { if (!qualificationOpen) return; dialogRef.current?.querySelector<HTMLInputElement>("input")?.focus(); const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") closeQualification(); }; document.addEventListener("keydown", onKeyDown); return () => { document.removeEventListener("keydown", onKeyDown); openerRef.current?.focus(); }; }, [qualificationOpen]);
  const submitQualification = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!qualification.name.trim() || !qualification.company.trim() || !qualification.operation.trim() || !qualification.process.trim()) { setFormError("Preencha os quatro campos para continuar."); return; } const url = buildQualifiedSalesWhatsAppUrl(process.env.NEXT_PUBLIC_CHECKFLOW_SALES_WHATSAPP, qualification); if (!url) { setFormError("O canal comercial ainda não está configurado neste ambiente."); return; } window.open(url, "_blank", "noopener,noreferrer"); };
  const setField = (field: keyof Qualification) => (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => setQualification(current => ({ ...current, [field]: event.target.value }));
  const pilot = <PilotCta onOpen={() => openQualification()} />;
  return <main className="marketing-shell">
    <header className="marketing-nav"><a className="marketing-brand" href="#inicio" aria-label="CheckFlow, início"><span>✓</span>CheckFlow</a><nav aria-label="Navegação principal"><a href="#demonstracao">Demonstração</a><a href="#produto">Produto</a><a href="#como-funciona">Como funciona</a><a href="#piloto">Piloto</a></nav><a className="marketing-login" href="/auth">Entrar <Arrow /></a></header>
    <section className="marketing-hero" id="inicio" aria-labelledby="hero-title"><div className="marketing-hero-copy"><p className="marketing-kicker">CONTROLE OPERACIONAL PARA EQUIPES</p><h1 id="hero-title">Sua operação sob controle.<br />Mesmo quando você não está olhando.</h1><p className="marketing-lead">O CheckFlow organiza processos operacionais, define responsáveis, registra evidências e mostra o que foi feito, o que deu errado e o que precisa ser corrigido.</p><div className="marketing-actions">{pilot}<a className="marketing-button secondary" href="#demonstracao">Ver o CheckFlow em ação</a></div><p className="marketing-helper">Para restaurantes, bares, buffets, eventos e equipes de operação.</p></div><ProductPreview /></section>
    <section className="marketing-section marketing-problem" aria-labelledby="problem-title"><div><p className="marketing-kicker">VISIBILIDADE OPERACIONAL</p><h2 id="problem-title">Você sabe o que realmente aconteceu na sua operação hoje?</h2></div><div className="marketing-problem-content"><div className="marketing-questions">{["Foi feito?", "Quem fez?", "Que horas?", "Tem foto?", "O problema foi corrigido?", "Quem ficou responsável?"].map(question => <span key={question}>{question}</span>)}</div><p>Quando essas respostas dependem de memória, mensagens ou de perguntar para alguém, o gestor não possui visibilidade suficiente da operação.</p></div></section>
    <section className="marketing-section marketing-demo" id="demonstracao" aria-labelledby="demo-title"><div className="marketing-centered-heading"><p className="marketing-kicker">DEMONSTRAÇÃO</p><h2 id="demo-title">Veja o CheckFlow em ação</h2><p>Do responsável à evidência e ao acompanhamento, em um fluxo operacional claro.</p></div><DemoVideo /></section>
    <section className="marketing-section marketing-product-section" id="produto" aria-labelledby="product-title"><div className="marketing-product-copy"><p className="marketing-kicker">PRODUTO REAL</p><h2 id="product-title">Da tarefa à evidência.</h2><p>O processo fica registrado: execução mobile, responsáveis, evidências, não conformidades, plano de ação e histórico.</p><ul><li><Check />Execução mobile</li><li><Check />Responsáveis e evidências</li><li><Check />Não conformidades e plano de ação</li><li><Check />Acompanhamento e histórico</li></ul></div><ProductDetail /></section>
    <section className="marketing-section" id="como-funciona" aria-labelledby="how-title"><div className="marketing-centered-heading"><p className="marketing-kicker">UM FLUXO CLARO</p><h2 id="how-title">Da rotina ao acompanhamento, sem depender de cobrança manual.</h2></div><ol className="marketing-steps">{processSteps.map(([number, title, text]) => <li key={number}><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></section>
    <section className="marketing-section" aria-labelledby="uses-title"><div className="marketing-centered-heading"><p className="marketing-kicker">CASOS DE USO</p><h2 id="uses-title">Um sistema. Diferentes rotinas operacionais.</h2></div><div className="marketing-use-grid">{[["Restaurantes", "Abertura · Fechamento · Higiene · Estoque"], ["Bares", "Abertura · Mise en place · Conferência"], ["Eventos", "Montagem · Operação · Desmontagem"], ["Buffets", "Preparação · Cozinha · Salão"]].map(([title,text]) => <article key={title}><span className="marketing-use-icon">↗</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="marketing-section marketing-manager" aria-labelledby="manager-title"><div><p className="marketing-kicker">VISÃO DO GESTOR</p><h2 id="manager-title">Pare de perguntar se foi feito.<br />Veja.</h2><p>Acompanhe o contexto de cada execução em um só lugar.</p></div><ManagerPreview /></section>
    <section className="marketing-pilot" id="piloto" aria-labelledby="pilot-title"><div className="marketing-pilot-copy"><p className="marketing-kicker">PILOTO CHECKFLOW</p><h2 id="pilot-title">Comece por um processo real.</h2><p>Escolha uma rotina importante da sua operação. Nós ajudamos a estruturá-la no CheckFlow e sua equipe testa durante 14 dias.</p><div className="marketing-pilot-points"><span>1 organização</span><i>+</i><span>1 processo operacional</span><i>+</i><span>equipe pequena</span><i>+</i><span>14 dias</span></div><small>Implantação assistida, com estruturação inicial em até 48 horas.</small><div className="marketing-pilot-action">{pilot}{!salesWhatsAppUrl && <p id="sales-contact-pending" role="status">O canal comercial ainda não está configurado neste ambiente.</p>}</div></div><div className="marketing-pilot-aside"><Check /><h3>Implantação assistida</h3><p>O piloto começa por uma rotina que sua equipe já precisa executar. A configuração é feita junto com você.</p></div></section>
    <section className="marketing-section marketing-faq" aria-labelledby="faq-title"><div className="marketing-centered-heading"><p className="marketing-kicker">DÚVIDAS FREQUENTES</p><h2 id="faq-title">O que você precisa saber antes de começar.</h2></div><div>{questions.map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
    <section className="marketing-final" aria-labelledby="final-title"><p className="marketing-kicker">PRÓXIMO PASSO</p><h2 id="final-title">Escolha um processo que hoje depende de cobrança manual.</h2><p>Vamos colocá-lo sob controle.</p>{pilot}</section><footer className="marketing-footer"><a className="marketing-brand" href="#inicio"><span>✓</span>CheckFlow</a><p>Controle operacional para equipes.</p><a href="/auth">Entrar</a></footer>
    {qualificationOpen && <div className="marketing-dialog-backdrop" onMouseDown={closeQualification}><div className="marketing-dialog" role="dialog" aria-modal="true" aria-labelledby="qualification-title" ref={dialogRef} onMouseDown={event => event.stopPropagation()}><button className="marketing-dialog-close" type="button" onClick={closeQualification} aria-label="Fechar qualificação">×</button><p className="marketing-kicker">PRÓXIMO PASSO</p><h2 id="qualification-title">Conte um pouco da sua operação.</h2><p>Usaremos estas informações somente para preparar sua mensagem no WhatsApp. Não inclua dados sensíveis.</p><form onSubmit={submitQualification} noValidate><label>Nome<input value={qualification.name} onChange={setField("name")} maxLength={60} autoComplete="name" /></label><label>Empresa<input value={qualification.company} onChange={setField("company")} maxLength={80} autoComplete="organization" /></label><label>Tipo de operação<select value={qualification.operation} onChange={setField("operation")}><option value="">Selecione</option><option>Restaurante</option><option>Bar</option><option>Buffet</option><option>Eventos</option><option>Outra operação</option></select></label><label>Primeiro processo a controlar<textarea value={qualification.process} onChange={setField("process")} maxLength={180} rows={3} aria-describedby="process-limit" /></label><small id="process-limit">{qualification.process.length}/180 caracteres</small>{formError && <p className="marketing-form-error" role="alert">{formError}</p>}<button className="marketing-button primary" type="submit">Continuar para o WhatsApp <Arrow /></button><button className="marketing-dialog-cancel" type="button" onClick={closeQualification}>Agora não</button></form></div></div>}
  </main>;
}

function DemoVideo() { return <div className="marketing-demo-frame">{demoVideoSrc ? <video className="marketing-demo-video" controls playsInline preload="metadata" poster={demoVideoPoster}><source src={demoVideoSrc} type="video/mp4" />Seu navegador não suporta vídeo HTML5.</video> : <div className="marketing-demo-fallback" aria-label="Prévia do produto; demonstração em vídeo em preparação"><div><span className="marketing-demo-badge">VÍDEO EM PREPARAÇÃO</span><h3>O fluxo operacional, do começo ao fim.</h3><p>Enquanto a demonstração gravada é finalizada, esta prévia mostra a interface real do CheckFlow.</p></div><ProductPreview compact /></div>}<p className="marketing-demo-caption">A demonstração em vídeo terá cerca de 30–45 segundos e poderá ser conectada sem alterar o layout.</p></div> }
function ProductPreview({ compact = false }: { compact?: boolean }) { return <div className={`marketing-preview${compact ? " compact" : ""}`} aria-label="Representação ilustrativa da tela de execução do CheckFlow"><div className="preview-top"><span className="preview-logo">✓</span><span>CheckFlow</span><i></i><span className="preview-avatar">MS</span></div><div className="preview-body"><aside><small>OPERAÇÃO</small><b>Visão geral</b><b className="selected">Checklists</b><b>Planos de ação</b><b>Histórico</b></aside><section><p>EXEMPLO ILUSTRATIVO</p><h3>Abertura do restaurante</h3><div className="preview-progress"><span>8 de 12 itens concluídos</span><b>67%</b><i><em /></i></div><article><span className="preview-done">✓</span><div><b>Conferir abertura do salão</b><small>Respondido por Marina Souza</small></div><strong>Concluído</strong></article><article><span className="preview-photo">▧</span><div><b>Registrar temperatura da câmara</b><small>Evidência fotográfica</small></div><strong className="preview-open">Em execução</strong></article><article><span className="preview-alert">!</span><div><b>Checar equipamentos</b><small>Não conformidade registrada</small></div><strong className="preview-warning">Atenção</strong></article></section></div></div> }
function ProductDetail() { return <div className="marketing-detail-product" aria-label="Detalhe de uma não conformidade e plano de ação"><header><span>Execução em andamento</span><b>08:14</b></header><div className="detail-product-title"><span className="preview-alert">!</span><div><small>NÃO CONFORMIDADE</small><h3>Equipamento sem identificação</h3></div></div><p>Registrada durante a abertura do restaurante.</p><div className="detail-action"><small>PLANO DE AÇÃO</small><strong>Identificar equipamento e atualizar registro</strong><div><span>Responsável: Carlos Lima</span><span>Prazo: hoje, 10:00</span></div></div><footer><span>Foto anexada</span><b>Ver no histórico <Arrow /></b></footer></div> }
function ManagerPreview() { return <div className="marketing-visibility-card"><div><span>Responsável</span><strong>Marina Souza</strong></div><div><span>Status</span><strong className="success">Concluído</strong></div><div><span>Horário</span><strong>18 set · 07:42</strong></div><div><span>Evidência</span><strong>Foto registrada</strong></div><div><span>Problema</span><strong className="warning">1 não conformidade</strong></div><div><span>Ação corretiva</span><strong>Responsável e prazo</strong></div><footer><span>Histórico</span><span>Execução registrada</span></footer></div> }
