begin read only;
with expected(index_name) as (values ('action_plans_one_per_non_conformity'),('attachments_storage_path_unique'),('attachments_one_per_answer')),
rows as (
select 'index_'||e.index_name report,case when i.oid is null or not x.indisvalid or not x.indisready then 'FAIL' else 'PASS' end status,coalesce(pg_get_indexdef(i.oid),'missing') count_or_value,'P1-04 unique workflow/evidence index.' interpretation from expected e left join pg_class i on i.relnamespace='public'::regnamespace and i.relname=e.index_name left join pg_index x on x.indexrelid=i.oid
union all select 'trigger_sync_checkflow_action_plan_non_conformity',case when exists(select 1 from pg_trigger t join pg_class c on c.oid=t.tgrelid where c.relnamespace='public'::regnamespace and c.relname='action_plans' and t.tgname='sync_checkflow_action_plan_non_conformity' and not t.tgisinternal) then 'PASS' else 'FAIL' end,'action_plans','P1-04 plan/NC synchronization trigger.'
union all select 'workflow_duplicate_or_missing_object_violations',case when count(*)=0 then 'PASS' else 'FAIL' end,count(*)::text,'Plan/attachment uniqueness and correction-object reference invariant.' from (select 1 from public.action_plans p where p.correction_comment is not null and (left(p.correction_comment,length(p.organization_id::text||'/action-plans/'||p.id::text||'/'))<>p.organization_id::text||'/action-plans/'||p.id::text||'/' or not exists(select 1 from storage.objects o where o.bucket_id='checkflow-evidence' and o.name=p.correction_comment)) union all select 1 from (select non_conformity_id from public.action_plans group by non_conformity_id having count(*)>1) x union all select 1 from (select storage_path from public.attachments group by storage_path having count(*)>1) x union all select 1 from (select answer_id from public.attachments where answer_id is not null group by answer_id having count(*)>1) x) q
)
select report,status,count_or_value,interpretation from rows order by report;
commit;
