begin read only;
with expected(table_name,trigger_name) as (values ('checklist_executions','aa_guard_checkflow_record_identity'),('checklist_assignments','aa_guard_checkflow_record_identity'),('execution_answers','aa_guard_checkflow_record_identity'),('attachments','aa_guard_checkflow_record_identity'),('non_conformities','aa_guard_checkflow_record_identity'),('action_plans','aa_guard_checkflow_record_identity'),('attachments','ab_guard_checkflow_evidence_object'),('action_plans','ab_guard_checkflow_evidence_object')),
rows as (
select 'trigger_'||e.table_name||'.'||e.trigger_name report,case when t.oid is null then 'FAIL' else 'PASS' end status,coalesce(pg_get_triggerdef(t.oid),'missing') count_or_value,'P1 forward identity/evidence guard trigger.' interpretation from expected e left join pg_class c on c.relnamespace='public'::regnamespace and c.relname=e.table_name left join pg_trigger t on t.tgrelid=c.oid and t.tgname=e.trigger_name and not t.tgisinternal
union all select 'legacy_pre_snapshot_preserved',case when count(*)=6 then 'PASS' else 'FAIL' end,count(*)::text,'Exactly six completed executions remain snapshotless legacy records before 2026-08-28; no snapshot is backfilled.' from public.checklist_executions where status='completed' and execution_snapshot is null and created_at<'2026-08-28T14:37:53.122342Z'::timestamptz and completed_at<'2026-08-28T14:37:53.122342Z'::timestamptz
union all select 'unexpected_snapshot_violations',case when count(*)=0 then 'PASS' else 'FAIL' end,count(*)::text,'No non-legacy execution has a missing or malformed snapshot.' from public.checklist_executions where id not in (select id from public.checklist_executions where status='completed' and execution_snapshot is null and created_at<'2026-08-28T14:37:53.122342Z'::timestamptz and completed_at<'2026-08-28T14:37:53.122342Z'::timestamptz) and (execution_snapshot is null or jsonb_typeof(execution_snapshot) is distinct from 'object' or jsonb_typeof(execution_snapshot->'sections') is distinct from 'array')
)
select report,status,count_or_value,interpretation from rows order by report;
commit;
